import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContext } from "@/lib/userContext";
import { getAuthenticatedAppForUser } from "@/lib/firebase/firebaseserver";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { currentUser } = await getAuthenticatedAppForUser(undefined);
  return (
    <AuthContext initialUser={currentUser}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </AuthContext>
  );
}
